name: push to staging
on:
  push:
    branches:
      - staging
jobs:
  push_to_external_repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: push to staging
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.HIMATI_WEBSITE_DEPLOY }}
          publish_dir: .
          external_repository: HimatiDev/himati-website-development
          publish_branch: main
          allow_empty_commit: true
          user_name: "HimatiDev"
          user_email: "himati.upmin@up.edu.ph"
